function fig = perChannelPCtrendScatter(data,pars)
%PERCHANNELPCTRENDSCATTER 3D scatter of coefficients for PC trends
%
%  fig = analyze.pc.perChannelPCtrendScatter(data,pars);
%
% Inputs
%  data - struct with fields
%           'coeff','score','day','explained','desc','epoch','Group','Area'
%  pars - parameters struct
%
% Output
%  fig  - Figure handle
%
% See also: analyze.pc, channel_cross_day_trends

fig = figure('Name',sprintf('%s Channel PC Coefficients',data.epoch),...
   'Color','w',...
   'Units','Normalized',...
   'Position',[0.6 0.3 0.3 0.3]); 
fig.UserData = data;
ax = axes(fig,...
   'XColor','k','YColor','k','LineWidth',1.5,...
   'NextPlot','add','FontName','Arial');
box(ax,'on');
grid(ax,'on');
for iG = 1:numel(pars.Group)
   for iA = 1:numel(pars.Area)
      c = pars.C.(pars.Group(iG)).(pars.Area(iA));
      scatter3(ax,...
         data.coeff(data.Group==pars.Group(iG) & data.Area==pars.Area(iA),1),...
         data.coeff(data.Group==pars.Group(iG) & data.Area==pars.Area(iA),2),...
         data.coeff(data.Group==pars.Group(iG) & data.Area==pars.Area(iA),3),...
         'filled',...
         'DisplayName',sprintf('%s::%s',pars.Group(iG),pars.Area(iA)),...
         'MarkerFaceAlpha',0.5,...
         'MarkerEdgeAlpha',0.75,...
         'SizeData',15,...
         'MarkerFaceColor',c,...
         'MarkerEdgeColor',c,...
         'Marker',pars.mrk.(pars.Group(iG)).(pars.Area(iA)));
   end
end
legend(ax,'FontName','Arial','TextColor','black');
view(ax,3);
title(ax,sprintf('%s Trend Coefficients',data.epoch),...
   'FontName','Arial','Color','k','FontWeight','bold');
xlabel(ax,'"Early" (PC-1)','FontName','Arial','Color','k','FontWeight','bold');
ylabel(ax,'"Mid" (PC-2)','FontName','Arial','Color','k','FontWeight','bold');
zlabel(ax,'"Late" (PC-3)','FontName','Arial','Color','k','FontWeight','bold');

end