function D = getNextDayStats(C)
%% GETNEXTDAYSTATS   Get stats for next day based on this day, if exists
%
%  D = GETNEXTDAYSTATS(C);
%
%  --------
%   INPUTS
%  --------
%     C     :     Table generated by EXPORTSUCCESSUNSUCCESSROTARYSTATS.
%
%  --------
%   OUTPUT
%  --------
%     D     :     Reduced table that matches prior day's (when available)
%                    rotary stats with present day's behavioral score.
%
% By: Max Murphy  v1.0  2019-06-18  Original version (R2017a)

%%
u = unique(C.Rat);
D = [];

figure('Name','Next Day Stats',...
   'Units','Normalized',...
   'Color','w',...
   'Position',[0.35 0.25 0.50 0.50]);
nRow = floor(sqrt(numel(u)));
nCol = ceil(numel(u)/nRow);

for iU = 1:numel(u)
   R = C(ismember(C.Rat,u{iU}),:);
   subplot(nRow,nCol,iU);
   
   scatter(R.pctUnsuccessful(1:(end-1)),R.Score(2:end),20,'k','filled');
   xlabel('% Unsuccessful','FontName','Arial','FontSize',14,'Color','k');
   ylabel('Score','FontName','Arial','FontSize',14,'Color','k');
   title(sprintf('%s (%s)',R.Rat{1},R.Group{1}),'FontName','Arial',...
      'FontSize',16,'Color','k');
   
   
%    for iR = 2:numel(R)
%       if (R.PostOpDay(iR) - R.PostOpDay(iR-1))==1
%          
%       end
%    end   
end


end