function fig = scatter_R2skew(e,varargin)
%SCATTER_R2SKEW Make scatter plot of R2 for a single animal
%
%  fig = analyze.jPCA.scatter_R2skew(e);
%  fig = analyze.jPCA.scatter_R2skew(e,'name',value,...);
%
% Inputs
%  e   - Reduced table with only one unique AnimalID 
%
% Output
%  fig - Graphics handle output

pars = struct;
pars.plane_colors = ...
   [0.0000    0.4470    0.7410; ...
    0.8500    0.3250    0.0980; ...
    0.9290    0.6940    0.1250; ...
    0.4940    0.1840    0.5560; ...
    0.4660    0.6740    0.1880; ...
    0.3010    0.7450    0.9330; ...
    0.6350    0.0780    0.1840  ...
    ];
pars.MarkerParams = {}; % 'Name',value pairs as go to @scatter normally
pars.LineParams = {};

fn = fieldnames(pars);
for iV = 1:2:numel(varargin)
   idx = strcmpi(fn,varargin{iV});
   if sum(idx)==1
      pars.(fn{idx}) = varargin{iV+1};
   end
end

figStr = sprintf('%s: jPCA Variance Captured',char(e.AnimalID(1)));
fig = figure(...
   'Name',figStr,...
   'Units','Normalized',...
   'Color','w',...
   'NumberTitle','off',...
   'Position',[0.2 0.2 0.5 0.5]);

ax = axes(fig,...
   'NextPlot','add',...
   'XColor','k',...
   'YColor','k',...
   'LineWidth',1.5,...
   'FontName','Arial'); 

col = pars.plane_colors(e.PlaneIndex,:);

splitapply(@(x,y,p,c)scatter(ax,x,y,'filled',...
   'DisplayName',sprintf('Plane-%02d',p(1)),...
   'MarkerFaceColor',c(1,:),...
   'MarkerEdgeColor',c(1,:),...
   pars.MarkerParams{:}),...
   e.PostOpDay,...
   e.R2_Skew,...
   e.PlaneIndex,...
   col,...
   e.PlaneIndex); 

ylim(ax,[0  1]);
xlim(ax,[-2 32]); 
ax.XTick = 0:7:28;

title(ax,sprintf('%s: R^2 jPCA',char(e.AnimalID(1))),...
   'FontName','Arial','Color','k','FontWeight','bold');
xlabel(ax,'Post-Op Day',...
   'FontName','Arial','Color','k','FontWeight','bold');
ylabel(ax,'R^2',...
   'FontName','Arial','Color','k','FontWeight','bold');
TX = nan(size(col,1),1);
TX(1:2:end) = randn(size(TX(1:2:end),1),1)*0.5 + max(e.PostOpDay) + 1;
TX(2:2:end) = randn(size(TX(2:2:end),1),1)*0.5 + min(e.PostOpDay) - 5;

splitapply(@(x,y,a,c,tx)analyze.stat.addLogisticRegression(ax,x,y,c(1,:),...
   linspace(min(e.PostOpDay),max(e.PostOpDay),100),...
   'addlabel',true,'TX',tx(1),'DisplayName',string(a(1)),...
   'LineStyle','-','LineWidth',1.5,pars.LineParams{:}),...
   e.PostOpDay,...
   e.R2_Skew,...
   e.AnimalID,...
   col,TX,...
   e.PlaneIndex);
legend(ax,...
   'Location','Best',...
   'FontName','Arial',...
   'TextColor','black');
end