function T = importDLC(filename,startRow,endRow,varargin)
%% IMPORTDLC Import numeric data from a text file as a matrix.
%
%  T = IMPORTDLC(filename);
%  T = IMPORTDLC(filename,startRow);
%  T = IMPORTDLC(filename,startRow,endRow);
%  T = IMPORTDLC(__,'NAME',value,...);
%
% Example:
%  F = dir('C:/path/to/labeled/files/*.csv');
%  T = cell(size(F),1);
%  for ii = 1:numel(F)
%     T{ii} = IMPORTDLC(F(ii).name);
%  end
%
%    See also TEXTSCAN.
%
% Auto-generated by MATLAB on 2018/07/23
% Modified by: Max Murphy

%% DEFAULTS
VAR_NAMES = {'frame', ...
             'd1_d_x','d1_d_y','d1_d_p', ... % Distal digit-1
             'd1_p_x','d1_p_y','d1_p_p', ... % Proximal digit-1
             'd2_d_x','d2_d_y','d2_d_p', ...
             'd2_p_x','d2_p_y','d2_p_p', ...
             'd3_d_x','d3_d_y','d3_d_p', ...
             'd3_p_x','d3_p_y','d3_p_p', ...
             'd4_d_x','d4_d_y','d4_d_p', ...
             'd4_p_x','d4_p_y','d4_p_p', ...
             'hand_x','hand_y','hand_p', ...
             'pellet_x','pellet_y','pellet_p', ...
             'support_x','support_y','support_p'}; % support hand

START_ROW = 4;
END_ROW = inf;
DELIM = ',';
END_OF_LINE = '\r\n';
DIR = 'P:\Rat\BilateralReach\Kinematics\RC';

%% PARSE VARARGIN
for iV = 1:2:numel(varargin)
   eval([upper(varargin{iV}) '=varargin{iV+1};']);
end

%% Initialize variables.
if nargin<=2
   startRow = START_ROW;
   endRow = END_ROW;
end

if nargin<=3
   endRow = END_ROW;
end

%% GET FORMAT FOR EACH LINE
nColumns = numel(VAR_NAMES); % Frame, then x,y,likelihood for each
formatSpec = repmat('%f',1,nColumns);
formatSpec = [formatSpec '%[^\n\r]'];

%% OPEN TEXT FILE
fileID = fopen(fullfile(DIR,filename),'r');

%% READ COLUMNS BASED ON FILE FORMAT
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, ...
            formatSpec, ...
            endRow(1)-startRow(1)+1, ...
            'Delimiter', DELIM, ...
            'TextType', 'string', ...
            'EmptyValue', NaN,...
            'HeaderLines', startRow(1)-1,...
            'ReturnOnError', false, ...
            'EndOfLine', END_OF_LINE);
         
for block=2:length(startRow)
   frewind(fileID);
   dataArrayBlock = textscan(fileID, ...
                     formatSpec, ...
                     endRow(block)-startRow(block)+1, ...
                     'Delimiter', DELIM, ...
                     'TextType', 'string', ...
                     'EmptyValue', NaN,...
                     'HeaderLines', startRow(block)-1,...
                     'ReturnOnError', false,...
                     'EndOfLine', END_OF_LINE);
   for col=1:length(dataArray)
      dataArray{col} = [dataArray{col};dataArrayBlock{col}];
   end
end

%% CLOSE TEXT FILE
fclose(fileID);

%% GENERATE OUTPUT
T = table(dataArray{1:end-1}, 'VariableNames', VAR_NAMES);

end