function getChannelInfo(ratName,tankLoc)
%% GETCHANNELINFO Import numeric data from a text file as a matrix.
%
%   GETCHANNELINFO(ratName)
%
% Auto-generated by MATLAB on 2018/07/30 06:29:24

if nargin < 2
   tankLoc = 'P:\Extracted_Data_To_Move\Rat\TDTRat';
end

%% Read animal metadata from ICMS data
animalPath = fullfile(tankLoc,ratName);
meta = getMetadata(fullfile(animalPath,'notes.txt'));

%% Create output struct
F = dir(fullfile(animalPath,[ratName '_2*']));
for iF = 1:numel(F)
   
   b = fullfile(animalPath,F(iF).name);
   s = fullfile(b,[F(iF).name '_wav-sneo_CAR_Spikes']);
   
   S = dir(fullfile(s,'*_ptrain_*.mat'));
   info = struct('file',cell(size(S)),...
      'probe',cell(size(S)),...
      'channel',cell(size(S)),...
      'ml',cell(size(S)),...
      'icms',cell(size(S)),...
      'area',cell(size(S)));
   for iS = 1:numel(S)
      info(iS,1) = makeInfoStruct(meta,S(iS).name);
   end
   fprintf(1,'Saving ChannelInfo for %s...',F(iF).name);
   save(fullfile(b,[F(iF).name '_ChannelInfo.mat']),'info','-v7.3');
   fprintf(1,'complete\n');
end


   function out = makeInfoStruct(meta,fname)
      out = struct;
      out.file = fname;
      
      strInfo = strsplit(fname,'_');
      out.probe = str2double(strInfo{6}(2));
      out.channel = str2double(strInfo{8}(1:3));
      
      idx = (out.probe-1)*16 + out.channel;
      
      out.ml = meta.ml{idx};
      out.icms = meta.icms{idx};
      out.area = meta.area{idx};
   end

end
