function exportSelectedVideos(Pa)
%EXPORTSELECTEDVIDEOS  Exports selected videos of interest
%
%  exportSelectedVideos(Pa);
%  
% Inputs
%  Pa     - Cell array of struct arrays returned by
%              analyze.jPCA.recover_channel_weights
%
% Output
%  -- none -- Exports .mp4 videos to the configured output folder, using
%             some subset of blocks that has been determined to be of
%             interest.
%
% See also: analyze.jPCA, analyze.jPCA.recover_channel_weights,
%           make.exportSkullPlotMovie, batch.exportMovies

SUB_FOLDER = 'exemplars';

make.exportSkullPlotMovie(Pa{18},...
   'trial',5,'plane',5,...
   'subtract_xc_mean',false,...
   'tag','_Example_Ischemia_Early_1',...
   'sub_folder',SUB_FOLDER);
make.exportSkullPlotMovie(Pa{18},...
   'trial',5,'plane',1,...
   'subtract_xc_mean',false,...
   'tag','_Example_Ischemia_Early_2',...
   'sub_folder',SUB_FOLDER);
make.exportSkullPlotMovie(Pa{36},...
   'trial',2,'plane',1,...
   'subtract_xc_mean',false,...
   'tag','_Example_Ischemia_Middle_2',...
   'sub_folder',SUB_FOLDER);
make.exportSkullPlotMovie(Pa{52},...
   'trial',2,'plane',1,...
   'subtract_xc_mean',false,...
   'tag','_Example_Ischemia_Late_1',...
   'sub_folder',SUB_FOLDER);
make.exportSkullPlotMovie(Pa{80},...
   'trial',5,'plane',1,...
   'subtract_xc_mean',false,...
   'tag','_Example_Intact_Early_1',...
   'sub_folder',SUB_FOLDER);
make.exportSkullPlotMovie(Pa{104},...
   'trial',2,'plane',1,...
   'subtract_xc_mean',false,...
   'tag','_Example_Ischemia_Middle_1',...
   'sub_folder',SUB_FOLDER);
make.exportSkullPlotMovie(Pa{116},...
   'trial',1,'plane',1,...
   'subtract_xc_mean',false,...
   'tag','_Example_Intact_Late_1',...
   'sub_folder',SUB_FOLDER);
make.exportSkullPlotMovie(Pa{116},...
   'trial',4,'plane',1,...
   'subtract_xc_mean',false,...
   'tag','_Example_Intact_Late_2',...
   'sub_folder',SUB_FOLDER);

end