%UNIT_LEARNING_STATS Use Mitz/Wise approach for Figs 2, S4: count spikes in pre-defined epochs to define activity
%
%  Sets up Figure 3: do trends in activity distinguish specific sub-types
%  of unit trends, and if so, are those trends more strongly associated
%  with one area or another?

clc;
clearvars -except r
if exist('r','var')==0
   r = utils.loadTables('rate');
else
   fprintf(1,'Found `r` (<strong>%d</strong> rows) in workspace.',size(r,1));
   k = 5;
   fprintf(1,'\n\t->\tPreview (%d rows):\n\n',k);
   disp(r(randsample(size(r,1),k),:));
end
if ismember('Group',r.Properties.VariableNames) && ~ismember('GroupID',r.Properties.VariableNames)
   r.Properties.VariableNames{'Group'} = 'GroupID';
end

%% Get subset for analysis
rSub = analyze.get_subset(r,'align',{'Grasp'});
[~,rSub] = analyze.trials.getChannelWeeklyGroupings(rSub,'animal',true);
% rSub = analyze.mergePredictionData

%%
clc;
% Create corresponding figures.
outPath = defaults.files('reach_extension_figure_dir');
if exist(outPath,'dir')==0
   mkdir(outPath);
end

% Initialize data output variables and data subset to pass to figures %
Data = struct;
mdl = struct;

% Generate figures corresponding to each epoch %
% % Pre-Grasp Figures % %
[fig,mdl.pre.all,Data.pre.all] = analyze.behavior.per_animal_area_mean_trends(rSub,...
   'N_Pre_Grasp',...
   'YLabel','Spike Count',...
   'FitOptions',{...
      'FitMethod','REMPL',...
      'Distribution','binomial',...
      'DummyVarCoding','effects',...
      'Link','logit' ...
      },...
   'LegendStyle','animals',...
   'LegendLocation','eastoutside',...
   'YLim',[0 80],...
   'Tag','All-Trials-Pre-Counts',...
   'ID',10,...
   'Title','Activity: Pre-Grasp (All Trials with Duration Exclusions)');
saveas(fig,fullfile(outPath,'Fig2a - Pre-Grasp Trends 95CB - Animal Mean Trends - All Trials.png'));
savefig(fig,fullfile(outPath,'Fig2a - Pre-Grasp Trends 95CB - Animal Mean Trends - All Trials.fig'));
delete(fig);

% % Reach Figures % %
[fig,mdl.reach.all,Data.reach.all] = analyze.behavior.per_animal_area_mean_trends(rSub,...
   'N_Reach',...
   'YLabel','Spike Count',...
   'RandomCovariates',{'Duration','Reach_Epoch_Duration'},...
   'FitOptions',{...
      'FitMethod','REMPL',...
      'Distribution','binomial',...
      'DummyVarCoding','effects',...
      'Link','logit' ...
      },...
   'LegendStyle','animals',...
   'LegendLocation','eastoutside',...
   'YLim',[0 80],...
   'Tag','All-Trials-Reach-Counts',...
   'ID',11,...
   'Title','Activity: Reach (All Trials with Duration Exclusions)');
saveas(fig,fullfile(outPath,'Fig2b - Reach Trends 95CB - Animal Mean Trends - All Trials.png'));
savefig(fig,fullfile(outPath,'Fig2b - Reach Trends 95CB - Animal Mean Trends - All Trials.fig'));
delete(fig);

% % Retract Figures % %
[fig,mdl.retract.all,Data.retract.all] = analyze.behavior.per_animal_area_mean_trends(rSub,...
   'N_Retract',...
   'YLabel','Spike Count',...
   'RandomCovariates',{'Duration','Retract_Epoch_Duration'},...
   'FitOptions',{...
      'FitMethod','REMPL',...
      'Distribution','binomial',...
      'DummyVarCoding','effects',...
      'Link','logit' ...
      },...
   'LegendStyle','animals',...
   'LegendLocation','eastoutside',...
   'YLim',[0 80],...
   'Tag','All-Trials-Retract-Counts',...
   'ID',12,...
   'Title','Activity: Retract (All Trials with Duration Exclusions)');
saveas(fig,fullfile(outPath,'Fig2c - Retract Trends 95CB - Animal Mean Trends - All Trials.png'));
savefig(fig,fullfile(outPath,'Fig2c - Retract Trends 95CB - Animal Mean Trends - All Trials.fig'));
delete(fig);

%% Make predictive models, holding out Performance
Data.pre.pred = Data.pre.all;
Data.pre.pred.GroupID = categorical(3-double(Data.pre.pred.GroupID),1:2,{'Ischemia','Intact'});
Data.reach.pred = Data.reach.all;
Data.reach.pred.GroupID = categorical(3-double(Data.reach.pred.GroupID),1:2,{'Ischemia','Intact'});
Data.retract.pred = Data.retract.all;
Data.retract.pred.GroupID = categorical(3-double(Data.retract.pred.GroupID),1:2,{'Ischemia','Intact'});

Data.pre.pred.N_Pre_Hat = predict(mdl.pre.all,Data.pre.pred).*Data.pre.pred.N_Total;
Data.reach.pred.N_Reach_Hat = predict(mdl.reach.all,Data.reach.pred).*Data.reach.pred.N_Total;
Data.retract.pred.N_Retract_Hat = predict(mdl.retract.all,Data.retract.pred).*Data.retract.pred.N_Total;
Data.pre.all.N_Pre_Hat = predict(mdl.pre.all,Data.pre.all).*Data.pre.all.N_Total;
Data.reach.all.N_Reach_Hat = predict(mdl.reach.all,Data.reach.all).*Data.reach.all.N_Total;
Data.retract.all.N_Retract_Hat = predict(mdl.retract.all,Data.retract.all).*Data.retract.all.N_Total;

rSub = analyze.get_subset(r,'align',{'Grasp'});
rWeek = analyze.trials.getChannelWeeklyGroupings(rSub,'animal',true);
rSub = analyze.behavior.mergePredictionData(rSub,Data);
rSub = analyze.behavior.mergeRatePerformance(rSub,false);

%% Fit Error Prediction models
S = struct(...
   'Link',@(mu)sqrt(asin(mu)./(pi/2)), ...
   'Derivative',@(mu)1./(sqrt(2*pi).*sqrt(1 - mu.^2).*sqrt(asin(mu))), ...
   'SecondDerivative',@(mu)sqrt(2/pi).*((mu./(2.*(1-mu.^2).^(3/2).*sqrt(asin(mu))))-(1./(4.*(1-mu.^2).*asin(mu).^(3/2)))), ...
   'Inverse',@(y)sin((y.^2).*(pi/2))...
   );
tic; fprintf(1,'Fitting classification model for <strong>PRE</strong> phase...');
mdl.pre.outcome.id = 10;
mdl.pre.outcome.tag = 'PRE-Outcome-Classifier';
mdl.pre.outcome.mdl = fitglme(rSub,...
   'Labels~GroupID*Area*PostOpDay+Performance_mu+epsilon_pre+(1+Performance_mu|AnimalID)+(1+epsilon_pre|ChannelID)',...
   'FitMethod','REMPL',...
   'Distribution','binomial',...
   'Link',S,...
   'BinomialSize',ones(size(rSub,1),1),...
   'DummyVarCoding','effects');
fprintf(1,'complete (%5.2f sec)\n',toc);
tic; fprintf(1,'Fitting classification model for <strong>REACH</strong> phase...');
mdl.reach.outcome.id = 11;
mdl.reach.outcome.tag = 'REACH-Outcome-Classifier';
mdl.reach.outcome.mdl = fitglme(rSub,...
   'Labels~GroupID*Area*PostOpDay+Performance_mu+epsilon_reach+(1+Performance_mu|AnimalID)+(1+epsilon_reach|ChannelID)',...
   'FitMethod','REMPL',...
   'Distribution','binomial',...
   'Link',S,...
   'BinomialSize',ones(size(rSub,1),1),...
   'DummyVarCoding','effects');
fprintf(1,'complete (%5.2f sec)\n',toc);
tic; fprintf(1,'Fitting classification model for <strong>RETRACT</strong> phase...');
mdl.retract.outcome.id = 12;
mdl.retract.outcome.tag = 'RETRACT-Outcome-Classifier';
mdl.retract.outcome.mdl = fitglme(rSub,...
   'Labels~GroupID*Area*PostOpDay+Performance_mu+epsilon_retract+(1+Performance_mu|AnimalID)+(1+epsilon_retract|ChannelID)',...
   'FitMethod','REMPL',...
   'Distribution','binomial',...
   'BinomialSize',ones(size(rSub,1),1),...
   'Link',S,...
   'DummyVarCoding','effects');
fprintf(1,'complete (%5.2f sec)\n',toc);

%% Display classification model info
clc;
utils.displayModel(mdl.pre.outcome);
utils.displayModel(mdl.reach.outcome);
utils.displayModel(mdl.retract.outcome);

%% Make figure to show predictive model result: Pre Phase
fig = analyze.stat.plotROC(mdl.pre.outcome.mdl);
saveas(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Pre Counts - All.png'));
savefig(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Pre Counts - All.fig'));
delete(fig);

fig = analyze.stat.batchROC(mdl.pre.outcome.mdl,'GroupID*Area*Week','Ischemia');
saveas(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Pre Counts - Ischemia.png'));
savefig(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Pre Counts - Ischemia.fig'));
delete(fig);

fig = analyze.stat.batchROC(mdl.pre.outcome.mdl,'GroupID*Area*Week','Intact');
saveas(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Pre Counts - Intact.png'));
savefig(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Pre Counts - Intact.fig'));
delete(fig);

%% Make figure to show predictive model result: Reach Phase
fig = analyze.stat.plotROC(mdl.reach.outcome.mdl);
saveas(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Reach Counts - All.png'));
savefig(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Reach Counts - All.fig'));
delete(fig);

fig = analyze.stat.batchROC(mdl.reach.outcome.mdl,'GroupID*Area*Week','Ischemia');
saveas(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Reach Counts - Ischemia.png'));
savefig(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Reach Counts - Ischemia.fig'));
delete(fig);

fig = analyze.stat.batchROC(mdl.reach.outcome.mdl,'GroupID*Area*Week','Intact');
saveas(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Reach Counts - Intact.png'));
savefig(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Reach Counts - Intact.fig'));
delete(fig);

%% Make figure to show predictive model result: Retract Phase
fig = analyze.stat.plotROC(mdl.retract.outcome.mdl);
saveas(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Retract Counts - All.png'));
savefig(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Retract Counts - All.fig'));
delete(fig);

fig = analyze.stat.batchROC(mdl.retract.outcome.mdl,'GroupID*Area*Week','Ischemia');
saveas(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Retract Counts - Ischemia.png'));
savefig(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Retract Counts - Ischemia.fig'));
delete(fig);

fig = analyze.stat.batchROC(mdl.retract.outcome.mdl,'GroupID*Area*Week','Intact');
saveas(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Retract Counts - Intact.png'));
savefig(fig,fullfile(outPath,'Fig3 - Outcome Prediction ROC - Retract Counts - Intact.fig'));
delete(fig);

%% Get Area-Under-Curve statistic for different weekly-groupings
rWeek = analyze.stat.addWeeklyROCdata(rWeek,mdl);

%% Make figure for Area-Under Curve trends
fig = figure('Name','Weekly AUC Trends','Color','w'); 
gCats = categorical(strcat(string(rWeek.GroupID),"::",string(rWeek.Area)));
gplotmatrix(rWeek.Week+double(gCats).*0.1,...
   [rWeek.Pre_AUC, rWeek.Reach_AUC, rWeek.Retract_AUC],...
   gCats,...
   [0.9 0.1 0.1; 0.9 0.1 0.1; 0.1 0.1 0.9; 0.1 0.1 0.9],...
   'x.os',[],'on','hist',{'Week'},{'AUC_{Pre}','AUC_{Reach}','AUC_{Retract}'});
ax = findobj(fig.Children,'-depth',0,'Tag','');
set(ax,'YLim',[0 1],'XColor','k','YColor','k','FontName','Arial','LineWidth',1.25);
set(findobj(fig.Children,'Tag','legend'),'Position',[0.3 0.85 0.25 0.089]);
saveas(fig,fullfile(outPath,'Fig3 - Weekly Classifier AUC by Group Area and Phase.png'));
savefig(fig,fullfile(outPath,'Fig3 - Weekly Classifier AUC by Group Area and Phase.fig'));
delete(fig);

%% Make statistical model for AUC Trends
mdl.pre.AUC.id  = 10;
mdl.pre.AUC.tag = 'Weekly-Pre-ROC-AUC';
mdl.pre.AUC.mdl = fitglme(rWeek,...
   'Pre_AUC~GroupID*Week+(1+Area|AnimalID)',...
   'FitMethod','REMPL',...
   'Distribution','normal',...
   'Link',S,...
   'Exclude',isnan(rWeek.Pre_AUC),...
   'DummyVarCoding','effects');

mdl.reach.AUC.id  = 11;
mdl.reach.AUC.tag = 'Weekly-Reach-ROC-AUC';
mdl.reach.AUC = fitglme(rWeek,...
   'Reach_AUC~GroupID*Week+(1+Area|AnimalID)',...
   'FitMethod','REMPL',...
   'Distribution','normal',...
   'Link',S,...
   'Exclude',isnan(rWeek.Pre_AUC),...
   'DummyVarCoding','effects');

mdl.retract.AUC.id  = 12;
mdl.retract.AUC.tag = 'Weekly-Retract-ROC-AUC';
mdl.retract.AUC = fitglme(rWeek,...
   'Retract_AUC~GroupID*Week+(1+Area|AnimalID)',...
   'FitMethod','REMPL',...
   'Distribution','normal',...
   'Link',S,...
   'Exclude',isnan(rWeek.Pre_AUC),...
   'DummyVarCoding','effects');

%% Display AUC model info
clc;
utils.displayModel(mdl.pre.AUC);
utils.displayModel(mdl.reach.AUC);
utils.displayModel(mdl.retract.AUC);

%% Do multi-model prediction for trends at the "Week" level
rSub_s = rSub;
rSub_s.Properties.UserData.Excluded(rSub_s.Outcome=="Unsuccessful") = [];
rSub_s(rSub_s.Outcome=="Unsuccessful",:) = [];
[fig,mdl.pre.multi_mdl,T.pre_full] = analyze.behavior.multi_model_fit(rSub_s,...
   'N_Pre_Grasp','Title','Pre-Grasp Epoch','YLim',[0 250],...
   'DurationTrendVar','Duration');
saveas(fig,fullfile(outPath,'Fig2a - Pre Counts 95CB - Grouped Mean Trends - Successful Trials.png'));
savefig(fig,fullfile(outPath,'Fig2a - Pre Counts 95CB - Grouped Mean Trends - Successful Trials.fig'));
delete(fig);

[fig,mdl.reach.multi_mdl,T.reach_full] = analyze.behavior.multi_model_fit(rSub_s,...
   'N_Reach','Title','Reach Epoch','YLim',[0 250],...
   'SimpleModelFormula','%s~PostOpDayc+Reach_Epoch_Duration+Duration+(1+PostOpDay|AnimalID)',...
   'DurationTrendVar','Reach_Epoch_Duration');
saveas(fig,fullfile(outPath,'Fig2b - Reach Counts 95CB - Grouped Mean Trends - Successful Trials.png'));
savefig(fig,fullfile(outPath,'Fig2b - Reach Counts 95CB - Grouped Mean Trends - Successful Trials.fig'));
delete(fig);

[fig,mdl.retract.multi_mdl,T.retract_full] = analyze.behavior.multi_model_fit(rSub_s,...
   'N_Retract','Title','Retract Epoch','YLim',[0 250],...
   'SimpleModelFormula','%s~PostOpDayc+Retract_Epoch_Duration+Duration+(1+PostOpDay|AnimalID)',...
   'DurationTrendVar','Retract_Epoch_Duration');
saveas(fig,fullfile(outPath,'Fig2c - Retract Counts 95CB - Grouped Mean Trends - Successful Trials.png'));
savefig(fig,fullfile(outPath,'Fig2c - Retract Counts 95CB - Grouped Mean Trends - Successful Trials.fig'));
delete(fig);

%% Get prediction models first
rWeek_s = analyze.trials.getChannelWeeklyGroupings(rSub_s,'animal',true);

mdl.pre.predict.id = 10;
mdl.pre.predict.tag = 'Weekly-Pre-Predicted_Successes';
mdl.pre.predict.mdl = fitglme(rWeek_s,...
   'n_Pre_mean~Week+Duration+(1+Week|AnimalID)',...
   'FitMethod','REMPL',...
   'Distribution','binomial',...
   'Link','logit',...
   'BinomialSize',rWeek_s.n_Total,...
   'Weights',rWeek_s.n_Blocks,...
   'DummyVarCoding','effects');

mdl.reach.predict.id = 11;
mdl.reach.predict.tag = 'Weekly-Reach-Predicted_Successes';
mdl.reach.predict.mdl = fitglme(rWeek_s,...
   'n_Reach_mean~Week+Reach_Epoch_Duration+Duration+n_Pre_mean+(1+Week|AnimalID)',...
   'FitMethod','REMPL',...
   'Distribution','binomial',...
   'Link','logit',...
   'BinomialSize',rWeek_s.n_Total,...
   'Weights',rWeek_s.n_Blocks,...
   'DummyVarCoding','effects');

mdl.retract.predict.id = 12;
mdl.retract.predict.tag = 'Weekly-Retract-Predicted_Successes';
mdl.retract.predict.mdl = fitglme(rWeek_s,...
   'n_Retract_mean~Week+Retract_Epoch_Duration+Duration+n_Pre_mean+(1+Week|AnimalID)',...
   'FitMethod','REMPL',...
   'Distribution','binomial',...
   'Link','logit',...
   'BinomialSize',rWeek_s.n_Total,...
   'Weights',rWeek_s.n_Blocks,...
   'DummyVarCoding','effects');
disp(mdl.pre.predict.mdl.Rsquared);
disp(mdl.reach.predict.mdl.Rsquared);
disp(mdl.retract.predict.mdl.Rsquared);

% Use prediction values in subsequent models
rWeek_s.n_Pre_pred = predict(mdl.pre.predict.mdl,rWeek_s).*rWeek_s.n_Total;
rWeek_s.n_Reach_pred = predict(mdl.reach.predict.mdl,rWeek_s).*rWeek_s.n_Total;
rWeek_s.n_Retract_pred = predict(mdl.retract.predict.mdl,rWeek_s).*rWeek_s.n_Total;
rWeek_s.Pre_err = rWeek_s.n_Pre_mean - rWeek_s.n_Pre_pred;
rWeek_s.Reach_err = rWeek_s.n_Reach_mean - rWeek_s.n_Reach_pred;
rWeek_s.Retract_err = rWeek_s.n_Retract_mean - rWeek_s.n_Retract_pred;

%% Fit GLME for weekly/channel grouped count data
% Make model for spike counts during "Pre" or "Baseline" epoch

mdl.pre.detrended.id = 10;
mdl.pre.detrended.tag = 'Weekly-Pre-Detrended-Count-Successes';
mdl.pre.detrended.mdl = fitglme(rWeek_s,...
   'n_Pre_mean~GroupID*Area+(1+n_Pre_pred|AnimalID)',...
   'FitMethod','REMPL',...
   'Distribution','binomial',...
   'Link','logit',...
   'BinomialSize',rWeek_s.n_Total,...
   'Weights',rWeek_s.n_Blocks,...
   'DummyVarCoding','effects');

% Make model for spike counts during "Reach" epoch
mdl.reach.detrended.id = 11;
mdl.reach.detrended.tag = 'Weekly-Reach-Detrended-Count-Successes';
mdl.reach.detrended.mdl = fitglme(rWeek_s,...
   'n_Reach_mean~GroupID*Area+(1+n_Reach_pred|AnimalID)',...
   'FitMethod','REMPL',...
   'Distribution','binomial',...
   'Link','logit',...
   'BinomialSize',rWeek_s.n_Total,...
   'Weights',rWeek_s.n_Blocks,...
   'DummyVarCoding','effects');


% Make model for spike counts during "Retract" epoch
mdl.retract.detrended.id = 12;
mdl.retract.detrended.tag = 'Weekly-Retract-Detrended-Count-Successes';
mdl.retract.detrended.mdl = fitglme(rWeek_s,...
   'n_Retract_mean~GroupID*Area+(1+n_Retract_pred|AnimalID)',...
   'FitMethod','REMPL',...
   'Distribution','binomial',...
   'Link','logit',...
   'BinomialSize',rWeek_s.n_Total,...
   'Weights',rWeek_s.n_Blocks,...
   'DummyVarCoding','effects');

%% Make tables
% Make table for individual animal effects
writetable(rWeek_s,fullfile(defaults.files('local_tank'),'TABLE-S4.xlsx'));

% Aggregate and test random effects to get significance by
% {Group,Area,Week}
T = struct;
% fcn = struct('mu',@(x)nanmean(x),'sigma',@(x)nanstd(x));
% T.pre= analyze.stat.groupLevelTests(rWeek_s,mdl.pre.weeks,rSub,fcn,{'N_Pre_Grasp'});
T.pre = analyze.stat.weekTrendTable(mdl.pre.detrended.mdl);
writetable(T.pre,fullfile(defaults.files('local_tank'),'TABLE-1.xlsx'),'Sheet','N_PRE');
fig = analyze.trials.plotTableData(T,'Pre');
saveas(fig,fullfile(outPath,'Fig2d - Pre Weekly Group Area Count Trends - Successes.png'));
savefig(fig,fullfile(outPath,'Fig2d - Pre Weekly Group Area Count Trends - Successes.fig'));
delete(fig);

% T.reach = analyze.stat.groupLevelTests(rWeek_s,mdl.reach.weeks,rSub,fcn,{'N_Reach'});
T.reach = analyze.stat.weekTrendTable(mdl.reach.detrended.mdl);
writetable(T.reach,fullfile(defaults.files('local_tank'),'TABLE-1.xlsx'),'Sheet','N_REACH');
fig = analyze.trials.plotTableData(T,'Reach');
saveas(fig,fullfile(outPath,'Fig2e - Reach Weekly Group Area Count Trends - Successes.png'));
savefig(fig,fullfile(outPath,'Fig2e - reach Weekly Group Area Count Trends - Successes.fig'));
delete(fig);

% T.retract = analyze.stat.groupLevelTests(rWeek_s,mdl.retract.weeks,rSub,fcn,{'N_Retract'});
T.retract = analyze.stat.weekTrendTable(mdl.retract.detrended.mdl);
writetable(T.retract,fullfile(defaults.files('local_tank'),'TABLE-1.xlsx'),'Sheet','N_RETRACT');
fig = analyze.trials.plotTableData(T,'Retract');
saveas(fig,fullfile(outPath,'Fig2f - Retract Weekly Group Area Count Trends - Successes.png'));
savefig(fig,fullfile(outPath,'Fig2f - Retract Weekly Group Area Count Trends - Successes.fig'));
delete(fig);

%% Display model outputs
clc;
utils.displayModel(mdl.pre.multi_mdl);
utils.displayModel(mdl.reach.multi_mdl);
utils.displayModel(mdl.retract.multi_mdl);
utils.displayModel(mdl.pre.predict);
utils.displayModel(mdl.reach.predict);
utils.displayModel(mdl.retract.predict);
utils.displayModel(mdl.pre.detrended);
utils.displayModel(mdl.reach.detrended);
utils.displayModel(mdl.retract.detrended);

%% Save model outputs
tic; fprintf(1,'Saving Fig [2,S4] models...');
save(defaults.files('rate_models_pre_reach_retract_matfile'),'-struct','mdl');
fprintf(1,'complete\n'); 
fprintf(1,'\t->\t%6.2f seconds elapsed\n',toc);
utils.addHelperRepos();
sounds__.play('bell',0.8,-15);
