function fig = epochSpikeTrends(r,varName,T)
%EPOCHSPIKETRENDS Plot trends in spike rate for given epoch
%
%  fig = analyze.behavior.epochSpikeTrends(r,varName);
%  fig = analyze.behavior.epochSpikeTrends(r,varName,T);
%  fig = analyze.behavior.epochSpikeTrends(r,varName,timeVarName);
%
% Inputs
%  r           - Rate table with .Excluded UserData field, for Grasp
%                 alignment, where .Rate is binned spike counts.
%  varName     - Name of count variable
%  T           - Duration of epoch (seconds)
%     OR
%  timeVarName - Name of variable with duration of epoch (per trial)
%
% Output
%  fig         - Figure handle
%
% See also: analyze.behavior, unit_learning_stats

str = strrep(varName,'N_','');
str = strrep(str,'_',' ');

% % Generate groupings vectors % %
r(r.Properties.UserData.Excluded,:) = [];
Groupings = findgroups(r(:,{'Group','Area'}));
% Make Partial Dependence Plot (PDP) figure for Reach Fraction
fig = figure(...
   'Name',sprintf('Trends in spike count: %s',str),...
   'Color','w',...
   'Units','Normalized',...
   'Position',[0.3 0.3 0.4 0.4]);
ax = axes(fig,...
   'XColor','k','YColor','k',...
   'LineWidth',1.5,...
   'NextPlot','add',...
   'FontName','Arial');

if ischar(T)
   splitapply(@(x,n,t,group,area)scatter(ax,...
      x+randn(size(x))*0.15,... % Add jitter for visualization
      sqrt(n)./t,'filled',...
      'DisplayName',sprintf('%s::%s',string(group(1)),string(area(1))),...
      'Marker','o',...
      'MarkerEdgeColor','none',...
      'MarkerFaceAlpha',0.25,...
      'SizeData',t*10),...
      r.PostOpDay,r.(varName),r.(T),r.Group,r.Area,Groupings);
else
   splitapply(@(x,n,group,area)scatter(ax,...
      x+randn(size(x))*0.15,...
      sqrt(n)./T,'filled',...
      'DisplayName',sprintf('%s::%s',string(group(1)),string(area(1))),...
      'Marker','o',...
      'MarkerEdgeColor','none',...
      'MarkerFaceAlpha',0.25,...
      'SizeData',5),...
      r.PostOpDay,r.(varName),r.Group,r.Area,Groupings);
end

ylabel(ax,sprintf('\\surdspikes/sec (%s)',str),...
   'FontName','Arial','Color','k');
xlabel(ax,'Days from Surgery','FontName','Arial','Color','k');
title(ax,sprintf('Observed trends: %s',str),...
   'FontName','Arial','Color','k');
legend(ax,'TextColor','black','FontName','Arial');
       
end