function rSub = mergePredictionData(rSub,Data)
%MERGEPREDICTIONDATA Merge data from prediction models with data table
%
%  rSub = analyze.behavior.mergePredictionData(rSub,Data);
%
% Inputs
%  rSub - Table used in unit_learning_stats
%  Data - Struct of tables recovered from prediction models in
%           unit_learning_stats
%
% Output
%  rSub - Merged data table

analyze.behavior.mergeRatePerformance(rSub,false);
rSub = outerjoin(rSub,Data.pre.pred,...
   'Keys',{'AnimalID','PostOpDay','Area'},...
   'MergeKeys',true,...
   'Type','Left',...
   'RightVariables',{'N_Pre_Hat'});
rSub = outerjoin(rSub,Data.reach.pred,...
   'Keys',{'AnimalID','PostOpDay','Area'},...
   'MergeKeys',true,...
   'Type','Left',...
   'RightVariables',{'N_Reach_Hat'});
rSub = outerjoin(rSub,Data.retract.pred,...
   'Keys',{'AnimalID','PostOpDay','Area'},...
   'MergeKeys',true,...
   'Type','Left',...
   'RightVariables',{'N_Retract_Hat'});

rSub.N_Pre_Error = rSub.N_Pre_Grasp - rSub.N_Pre_Hat;
rSub.N_Reach_Error = rSub.N_Reach - rSub.N_Reach_Hat;
rSub.N_Retract_Error = rSub.N_Retract - rSub.N_Retract_Hat;
rSub.Labels = double(rSub.Outcome)-1;
end