function [fig,coeff,score] = plot_pc_summary(G,pc_indices)
%PLOT_PC_SUMMARY Plot PCs summarizing system fit
%
%  [fig,score] = analyze.stat.plot_pc_summary(G);
%  [fig,score] = analyze.stat.plot_pc_summary(G,pc_indices)
%
% Inputs
%  G     - Table in format returned by analyze.stat.get_fitted_table
%
% Output
%  fig   - matlab.ui.Figure graphics handle
%  coeff - Coefficients recovered via pca
%  score - Scores recovered via pca

if nargin < 2
   pc_indices = 1:3;
end

% Define variable labels here %
v = {'Peak Offset (s)', ...
    'Envelope Bandwidth (Hz)', ...
    'Oscillation Frequency (Hz)', ...
    'Linear Time Bias (Spike Rate)' ,...
    'Premotor Bias (Spike Rate)'};

[axParams,figParams,fontParams] = defaults.stat(...
   'axParams','figParams','fontParams');
Z = [...
   G.PeakOffset,         ...
   G.EnvelopeBW,         ...
   G.PeakFreq,           ...
   G.LinearTrendCoeff,   ...
   G.LinearTrendOffset  ...
     ];
[coeff,score,~,~,explained,~] = pca(Z);
fig = figure(...
   'Name','Principal Components of System Fit',...
   figParams{:}); 
ax = subplot(2,1,1); 
set(ax,axParams{:},'XTick',1:numel(explained),...
   'XLim',[0.5,numel(explained)+0.5],...
   'YLim',[0 105],...
   'YTick',[25 50 75 100]);
explained_c = cumsum(explained);
% Plot cumulative % explained as stem plot
h = stem(ax,1:numel(explained),explained_c,...
   'LineWidth',1.5,'Color','k',...
   'MarkerFaceColor','k',...
   'MarkerSize',20); 
h.Annotation.LegendInformation.IconDisplayStyle = 'off';
c = getColorMap(numel(pc_indices),'vibrant');
for i = 1:numel(pc_indices)
   thisPC = pc_indices(i);
   line(ax,thisPC,explained_c(thisPC),...
      'Color','w',...
      'Marker','o',...
      'MarkerFaceColor',c(i,:),...
      'MarkerSize',20,...
      'LineStyle','none',...
      'DisplayName',sprintf('PC-%02d',thisPC));
end
legend(ax,'Location','Best');
xlabel(ax,'PC',fontParams{:});
ylabel(ax,'% Explained',fontParams{:});
title(ax,'Cumulative Data Explained by PCs',fontParams{:}); 
ax = subplot(2,1,2); 
biplot(coeff(:,pc_indices),...
   'VarLabels',v,...
   'Scores',score(randi(size(score,1),1,100),pc_indices),...
   'Parent',ax,...
   'LineWidth',1.5);
set(ax,axParams{:});
xlabel(ax,sprintf('PC-%02d',pc_indices(1)),...
   'FontName','Arial','Color',c(1,:),'FontWeight','bold');
ylabel(ax,sprintf('PC-%02d',pc_indices(2)),...
   'FontName','Arial','Color',c(2,:),'FontWeight','bold');
zlabel(ax,sprintf('PC-%02d',pc_indices(3)),...
   'FontName','Arial','Color',c(3,:),'FontWeight','bold');
title(ax,'Component Weightings (100 Random Scores Shown)',...
   fontParams{:});
end
